name: myapp
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  get_it: ^7.7.0

dev_dependencies:
  architecture_linter: ^0.2.0
  dart_code_linter: ^1.1.1
  faker: ^2.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
